services:
    redis:
        image: redis:alpine
        container_name: next-limit-redis-test
        command: redis-server --requirepass ${REDIS_PASSWORD} --port ${REDIS_PORT}
        ports:
            - '${REDIS_PORT}:${REDIS_PORT}'
        healthcheck:
            test:
                [
                    'CMD',
                    'redis-cli',
                    '-p',
                    '${REDIS_PORT}',
                    '-a',
                    '${REDIS_PASSWORD}',
                    'ping',
                ]
            interval: 1s
            timeout: 3s
            retries: 30
